name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 8:30 PM PKT 
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          SHOW_TIME: true
          SHOW_TOTAL: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          LANG_COUNT: 10
          TIME_RANGE: all_time
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics 
          SHOW_MASKED_TIME: false
          SHOW_SHORT_INFO: true
